sudo: false

# Use node_js environnement
language: java

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=javad-250512
    - CLUSTER_NAME=pipedrive-cluster
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a

before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta

script:
  - ./mvnw test

before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deployment/deploy.sh
    skip_cleanup: true
    on:
      branch: master
