version: '3'
services:
  app:
    restart: always
    image: maven:3.6.1-jdk-8-alpine
    working_dir: /app
    environment:
      PIPEDRIVE_TOKEN: "Your Pipedrive Token"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run